name: Sync-Zscalar-IP-Ranges
on:
  repository_dispatch:

  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:

    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./Zscaler/SyncZscalerIPRanges.ps1      
